services:
  bookify.api:
    image: ${DOCKER_REGISTRY-}bookifyapi
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: Bookify.API/Dockerfile
    depends_on:
      - bookify-db

  bookify-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Bookify.Db
    environment:
      SA_PASSWORD: "Nanna2001!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./Bookify.API/.containers/database:/var/opt/mssql
    ports:
      - 1433:1433

  # bookify-idp:
  #   image: jboss/keycloak:latest
  #   container_name: Bookify.Idp
  #   environment:
  #     - KEYCLOAK_USER=admin
  #     - KEYCLOAK_PASSWORD=admin
  #     - KEYCLOAK_IMPORT=/tmp/bookify-realm-export.json
  #   volumes:
  #     - ./Bookify.API/.containers/identity:/opt/jboss/keycloak/standalone/data
  #     - ./Bookify.API/.files/bookify-realm-support.json:/tmp/bookify-realm-export.json
  #   ports:
  #     - 18080:8008

